import BusinessCore
import CryptoKit
import Foundation

/// BitOS API uploader. The response is not trusted until the public object
/// is read back and its SHA-256 matches the exact rendered bytes.
struct BitosMediaUploader: Sendable {
    struct UploadFailure: LocalizedError { let message: String; var errorDescription: String? { message } }

    static let endpoint = URL(string: "https://social.bitos.space/api/media/upload")!

    func upload(bytes: Data, mimeType: String, filename: String = "meme.mp4") async throws -> (url: String, hash: String) {
        guard !bytes.isEmpty, bytes.count <= maxBitOSUploadBytes else {
            throw UploadFailure(message: "file out of bounds")
        }
        let localHash = SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined()
        var request = URLRequest(url: Self.endpoint)
        request.httpMethod = "POST"
        request.setValue(filename, forHTTPHeaderField: "X-Upload-Filename")
        request.setValue(localHash, forHTTPHeaderField: "X-SHA-256")
        request.setValue(mimeType, forHTTPHeaderField: "Content-Type")
        request.httpBody = bytes
        let (body, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse, (200...299).contains(http.statusCode) else {
            throw UploadFailure(message: "BitOS upload failed")
        }
        guard let payload = try? JSONSerialization.jsonObject(with: body) as? [String: Any],
              let rawURL = payload["url"] as? String,
              let url = URL(string: rawURL), url.scheme?.lowercased() == "https" else {
            throw UploadFailure(message: "BitOS upload returned no HTTPS media URL")
        }
        // Until the BitOS API returns a server hash, read back the object.
        // This is deliberately blocking: media must be verified before sign.
        let (stored, remoteResponse) = try await URLSession.shared.data(from: url)
        guard let remote = remoteResponse as? HTTPURLResponse, (200...299).contains(remote.statusCode) else {
            throw UploadFailure(message: "BitOS upload could not be verified")
        }
        let remoteHash = SHA256.hash(data: stored).map { String(format: "%02x", $0) }.joined()
        guard remoteHash == localHash else {
            throw UploadFailure(message: "BitOS stored different bytes than were uploaded")
        }
        return (rawURL, localHash)
    }

    static let maxBitOSUploadBytes = 100 * 1024 * 1024
}

/// Small video publishes require both verified destinations. The BitOS URL is
/// canonical in NIP-71; Blossom is a verified availability replica.
struct MemeVideoUploader: Sendable {
    private let bitos = BitosMediaUploader()
    private let blossom: BlossomUploader

    init(bridge: BusinessCoreBridge = BusinessCoreBridge()) { blossom = BlossomUploader(bridge: bridge) }

    func upload(
        bytes: Data,
        mimeType: String,
        identity: IdentityStore,
        onStage: ((BlossomUploader.UploadStage) -> Void)? = nil
    ) async throws -> (url: String, hash: String, mime: String, size: Int) {
        let canonical = try await bitos.upload(bytes: bytes, mimeType: mimeType)
        // Mirrors shared MemeUploadRouting; the prebuilt XCFramework is
        // regenerated by the release build before exposing new KMP symbols.
        if bytes.count < dualUploadMaxBytes {
            _ = try await blossom.upload(
                bytes: bytes, mimeType: mimeType, identity: identity,
                serverUrl: "https://blossom.primal.net", onStage: onStage
            )
        }
        return (canonical.url, canonical.hash, mimeType, bytes.count)
    }

    private let dualUploadMaxBytes = 20 * 1024 * 1024
}
